feat: Add support for `Tauri.toml` config
tauri-apps/tauri-action pull request #375
Opened 2023-02-06 14:44 UTC by FabianLars

2023-02-21 23:48 UTC, amrbashir requested changes

2023-02-21 23:48 UTC, amrbashir commented on src/build.ts
> +  const info = getInfo(root, buildOpts.configPath ?? undefined);
usually `??` is used for falling back to a truthy value, while here you are falling back to a falsy value and that doesn't make sense. Instead, change `buildOpts.configPath` type

2023-02-21 23:48 UTC, amrbashir commented on src/utils.ts
> +    ['**/tauri.conf.json', '**/tauri.conf.json5', '**/Tauri.toml'],
probably out of this PR scope, what about platform specific configs? I mean `tauri.macos.config.json`

2023-02-22 08:53 UTC, FabianLars commented on src/utils.ts
> +    ['**/tauri.conf.json', '**/tauri.conf.json5', '**/Tauri.toml'],
https://github.com/tauri-apps/tauri-action/issues/337 - will do in another pr since it involves merging configs.

2023-02-22 08:54 UTC, FabianLars commented on src/build.ts
> +  const info = getInfo(root, buildOpts.configPath ?? undefined);
whoops, that was just to make ts shut up quickly. forgot about it, thanks!

2023-02-22 09:36 UTC, FabianLars commented on src/build.ts
> +  const info = getInfo(root, buildOpts.configPath ?? undefined);
Actually there is some deeper logic error with the project initialization stuff too, but that may be a bigger change so i'll do that in a separate pr (it was broken before this pr anyway).

2023-02-22 11:18 UTC, amrbashir approved these changes

2023-02-22 12:01 UTC, merged