add workspace cargo manifest
tauri-apps/tauri-action pull request #558
Opened 2023-09-05 15:06 UTC by tr3ysmith

This is a potential fix for #557

This adds some logic to revert to the workspace manifest if version or name have the workspace key instead of a string.

This is currently untested.

2023-09-05 15:17 UTC, tr3ysmith commented
Currently testing on one of my workspace applications

2023-09-05 17:06 UTC, tr3ysmith commented
Initial test didn't change anything, going to try some other things

2023-09-21 18:36 UTC, FabianLars requested changes

2023-09-21 18:36 UTC, FabianLars commented on src/utils.ts
> +    }
I think it needs to be `workspaceManifest.workspace.package.abc` here. I didn't make it a commitable code suggestion because this will also need type changes for it to build.

2023-09-22 01:23 UTC, tr3ysmith commented
I'll need to test this tomorrow but hopefully that does it!

2023-09-26 11:13 UTC, FabianLars commented
Oh and one thing i missed is that you have to run `pnpm build` to rebuild the dist files (and commit them). Otherwise the changes won't be applied.

2023-10-05 12:09 UTC, FabianLars approved these changes
Thank you!

2023-10-05 12:10 UTC, FabianLars commented
welp, ci not agreeing with me there 😂

2023-10-05 12:12 UTC, merged