feat: add support for building with vue cli
tauri-apps/tauri-action pull request #60
Opened 2021-01-25 23:46 UTC by nklayman

If vue-cli-plugin-tauri is installed, it will run `yarn tauri:build` instead of `yarn tauri build`.

2021-01-27 09:31 UTC, Milo123459 approved these changes

2021-01-29 07:32 UTC, nklayman commented
Something is broken, seems like it's the `getDependency` function, but I'm really not sure. [Here is the failing run](https://github.com/nklayman/tauri-vue/actions/runs/514141769). I can't figure out what is wrong, maybe another pair of eyes can catch something.

2021-01-29 23:05 UTC, nklayman commented
Okay now that I've actually built the project it works. @jbolda can you review and merge please?

2021-01-29 23:46 UTC, lucasfernog commented on src/main.ts
> +        ? (usesYarn(root) ? 'yarn' : 'npm run') + ' tauri:build'
```suggestion
        ? (npmScript || (usesYarn(root) ? 'yarn' : 'npm run') + ' tauri:build')
```

2021-01-29 23:46 UTC, lucasfernog approved these changes

2021-01-30 00:14 UTC, nklayman commented on src/main.ts
> +        ? (usesYarn(root) ? 'yarn' : 'npm run') + ' tauri:build'
Oh yeah that's not a bad idea. However, the npm script is expected to be used like this: `yarn/npm run ${npmScript} build`. Is it a bad idea to make it function slightly differently in the case of the vue cli plugin? We would have to update the docs as well. At the very least it should probably still add `yarn/npm run` automatically.

2021-01-30 00:57 UTC, lucasfernog commented on src/main.ts
> +        ? (usesYarn(root) ? 'yarn' : 'npm run') + ' tauri:build'
I guess we could leave it the way you wrote since this action is mostly for simple apps

2021-01-30 01:13 UTC, nklayman commented on src/main.ts
> +        ? (usesYarn(root) ? 'yarn' : 'npm run') + ' tauri:build'
Yeah I doubt people will change the script name, if someone needs to and opens and issue we can just add it then. Ready to merge IMO :+1:.

2021-01-30 03:11 UTC, jbolda requested changes
Seems to fit with the existing precedent you have with vue. We need to add a change file, then it's good to go.

2021-01-30 18:35 UTC, nklayman commented
Okay I added one, lmk if I did it right.

2021-01-30 18:48 UTC, nklayman commented
Alright there we go, fixed now.

2021-01-30 19:22 UTC, merged